### ISSUE TITLE
Typing lib should only be a requirement if Python is < 3.5

### ISSUE THREAD

**Issue by s2pstefan** [OCHA-DAP/hdx-python-utilities#2]
The requirement _typing==3.6.6_ is needed only for Python versions less than 3.5. Typing was moved to standard Python lib in 3.5 and on certain deployments such as AWS and Azure it creates issues. 

See also: https://fernandomc.com/posts/issues-with-typing-python-3/

I propose the modification of requirements.txt by changing 

**typing==3.6.6**

to:

**typing==3.6.6; python_version < '3.5'**

**Comment by mcarans** [comment]
I forgot to say that this was done and close the ticket.
